name: Test
on:
  push:
  pull_request:
  schedule: [{cron: '10 23 * * 1'}]  # M H d m w (Sat 23:10)
jobs:
  test:
    if: github.event_name != 'pull_request' || !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association)
    name: Test py${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: setup
      run: |
        mkdir epic
        touch epic/some.whl
        touch epic/some.whl.asc
        touch epic/source.tar.gz
    - id: action
      uses: ./.github/..
      with:
        password: pass
        check: false
        upload: false
        dist_dir: epic
        url: https://test.pypi.org
        gpg_key: ${{ secrets.GPG_KEY }}
    - name: test
      run: |
        [[ ${{ steps.action.outputs.whl }} == some.whl ]]
        [[ ${{ steps.action.outputs.whl_asc }} == some.whl.asc ]]
        [[ ${{ steps.action.outputs.targz }} == source.tar.gz ]]
        [[ -z "${{ steps.action.outputs.targz_asc }}" ]]
